       const words = [
        { group: '#0 全身に用いる単語', word: 'epi-', meaning: 'on top of' },
{ group: '#0 全身に用いる単語', word: 'peri-', meaning: 'around' },
{ group: '#0 全身に用いる単語', word: 'endo-', meaning: 'internal' },
{ group: '#0 全身に用いる単語', word: 'pro-', meaning: 'before' },
{ group: '#0 全身に用いる単語', word: 'para-', meaning: 'above, beside' },
{ group: '#0 全身に用いる単語', word: '-細胞', meaning: '-cyte' },
{ group: '#0 全身に用いる単語', word: '-芽細胞(-を産生する細胞)', meaning: '-blast' },
{ group: '#0 全身に用いる単語', word: '小～, small-', meaning: '-ulus' },
{ group: '#0 全身に用いる単語', word: '髄質', meaning: 'medulla' },
{ group: '#0 全身に用いる単語', word: '皮質', meaning: 'cortex' },
{ group: '#0 全身に用いる単語', word: '被膜', meaning: 'capsule' },
{ group: '#0 全身に用いる単語', word: '小体', meaning: 'corpuscle / body' },
{ group: '#0 全身に用いる単語', word: '膜', meaning: 'membrane' },
{ group: '#0 全身に用いる単語', word: '被膜, 層', meaning: 'tunica' },
{ group: '#0 全身に用いる単語', word: '叢, 網状組織', meaning: 'plexus' },
{ group: '#0 全身に用いる単語', word: '薄層, 板', meaning: 'lamina' },
{ group: '#0 全身に用いる単語', word: '薄板', meaning: 'lamella' },
{ group: '#0 全身に用いる単語', word: '索(大綱)', meaning: 'trabecula' },
{ group: '#0 全身に用いる単語', word: '腔', meaning: 'cavity' },
{ group: '#0 全身に用いる単語', word: '乳頭', meaning: 'papillae' },
{ group: '#0 全身に用いる単語', word: '鞘', meaning: 'sheath' },
{ group: '#0 全身に用いる単語', word: '括約筋', meaning: 'sphincter' },
{ group: '#0 全身に用いる単語', word: '腺', meaning: 'gland' },
{ group: '#0 全身に用いる単語', word: '漿液性の', meaning: 'serous' },
{ group: '#0 全身に用いる単語', word: '粘液性の', meaning: 'mucous' },
{ group: '#0 全身に用いる単語', word: '管', meaning: 'duct' },
{ group: '#0 全身に用いる単語', word: '細管', meaning: 'tubule / tubuli' },
{ group: '#0 全身に用いる単語', word: '毛細管', meaning: 'canaliculus' },
{ group: '#0 全身に用いる単語', word: '小動脈', meaning: 'arteriole' },
{ group: '#0 全身に用いる単語', word: '細網', meaning: 'reticulum' },
{ group: '#0 全身に用いる単語', word: '濾胞, 小胞', meaning: 'follicle' },
{ group: '#0 全身に用いる単語', word: 'こぶ, 結節', meaning: 'node' },
{ group: '#0 全身に用いる単語', word: '形質, プラズマ', meaning: 'plasma' },
{ group: '#1 上皮', word: '上皮', meaning: 'epithelium' },
{ group: '#1 上皮', word: '内皮', meaning: 'endothelium' },
{ group: '#1 上皮', word: '単層', meaning: 'simple' },
{ group: '#1 上皮', word: '重層', meaning: 'stratified' },
{ group: '#1 上皮', word: '扁平', meaning: 'squamous' },
{ group: '#1 上皮', word: '立方', meaning: 'cuboidal' },
{ group: '#1 上皮', word: '円柱', meaning: 'columnar' },
{ group: '#1 上皮', word: '(非/)角化', meaning: '(un/)keratinized' },
{ group: '#1 上皮', word: '偽重層(多列)', meaning: 'pseudostratified' },
{ group: '#1 上皮', word: '移行', meaning: 'transitional' },
{ group: '#1 上皮', word: '基底膜', meaning: 'basal membrane' },
{ group: '#1 上皮', word: '繊毛細胞', meaning: 'ciliated cell' },
{ group: '#1 上皮', word: '基底細胞', meaning: 'basal cell' },
{ group: '#1 上皮', word: '杯細胞', meaning: 'goblet cell' },
{ group: '#1 上皮', word: '刷子縁', meaning: 'brush border' },
{ group: '#1 上皮', word: '繊毛', meaning: 'cilia' },
{ group: '#1 上皮', word: '絨毛', meaning: 'villi' },
{ group: '#1 上皮', word: '微絨毛', meaning: 'microvilli' },
{ group: '#1 上皮', word: 'アクチンフィラメント', meaning: 'actin filament' },
{ group: '#1 上皮', word: '中間径フィラメント', meaning: 'intermediate filament' },
{ group: '#1 上皮', word: '微小管', meaning: 'microtubule' },
{ group: '#2 結合組織', word: '疎性結合組織', meaning: 'loose connective tissue' },
{ group: '#2 結合組織', word: '強靭(密性)結合組織', meaning: 'dense connective tissue' },
{ group: '#2 結合組織', word: '細網組織', meaning: 'reticular connective tissue' },
{ group: '#2 結合組織', word: '脂肪組織', meaning: 'adipose tissue' },
{ group: '#2 結合組織', word: '膠様組織', meaning: 'mucous connective tissue' },
{ group: '#2 結合組織', word: 'コラーゲン線維(膠原線維)', meaning: 'collagen fiber' },
{ group: '#2 結合組織', word: '細網線維', meaning: 'reticular fiber' },
{ group: '#2 結合組織', word: '弾性線維', meaning: 'elastic fiber' },
{ group: '#2 結合組織', word: '線維芽細胞', meaning: 'fibroblast' },
{ group: '#2 結合組織', word: '細網細胞', meaning: 'reticular cell' },
{ group: '#2 結合組織', word: '脂肪細胞', meaning: 'adipocyte' },
{ group: '#2 結合組織', word: '顆粒細胞(肥満細胞)', meaning: 'mast cell' },
{ group: '#2 結合組織', word: '閉鎖帯', meaning: 'zonula occludens' },
{ group: '#2 結合組織', word: 'タイト結合(=閉鎖帯)', meaning: 'tight junction' },
{ group: '#2 結合組織', word: '接着帯', meaning: 'zonula adherens' },
{ group: '#2 結合組織', word: 'デスモソーム(接着斑)', meaning: 'desmosome' },
{ group: '#2 結合組織', word: '閉鎖堤', meaning: 'terminal bar' },
{ group: '#2 結合組織', word: '接着複合体', meaning: 'junctional complex' },
{ group: '#2 結合組織', word: 'フォーカルアドヒージョン(局所接着)', meaning: 'focal adhesion' },
{ group: '#2 結合組織', word: 'ヘミデスモソーム', meaning: 'hemidesmosome' },
{ group: '#2 結合組織', word: 'ギャップ結合', meaning: 'gap junction' },
{ group: '#3 骨・軟骨', word: '軟骨前駆細胞', meaning: 'chondroprogenitor cell' },
{ group: '#3 骨・軟骨', word: '軟骨芽細胞', meaning: 'chondroblast' },
{ group: '#3 骨・軟骨', word: '軟骨細胞', meaning: 'chondrocyte' },
{ group: '#3 骨・軟骨', word: '軟骨小腔', meaning: 'cartilage lacuna' },
{ group: '#3 骨・軟骨', word: '軟骨膜', meaning: 'perichondrium' },
{ group: '#3 骨・軟骨', word: '硝子(ガラス)軟骨', meaning: 'hyaline cartilage' },
{ group: '#3 骨・軟骨', word: '弾性軟骨', meaning: 'elastic cartilage' },
{ group: '#3 骨・軟骨', word: '線維軟骨', meaning: 'fibrocartilage' },
{ group: '#3 骨・軟骨', word: '骨原性細胞', meaning: 'osteoprogenitor cell' },
{ group: '#3 骨・軟骨', word: '骨芽細胞', meaning: 'osteoblast' },
{ group: '#3 骨・軟骨', word: '骨細胞', meaning: 'osteocyte' },
{ group: '#3 骨・軟骨', word: '破骨細胞', meaning: 'osteoclast' },
{ group: '#3 骨・軟骨', word: '緻密骨', meaning: 'compact bone' },
{ group: '#3 骨・軟骨', word: '海綿骨', meaning: 'spongy bone' },
{ group: '#3 骨・軟骨', word: '髄腔', meaning: 'medullary cavity' },
{ group: '#3 骨・軟骨', word: '骨膜', meaning: 'periosteum' },
{ group: '#3 骨・軟骨', word: '外側線維層', meaning: 'outer fibrous layer' },
{ group: '#3 骨・軟骨', word: '内側細胞層', meaning: 'inner cellular layer' },
{ group: '#3 骨・軟骨', word: 'シャーピー線維', meaning: 'Sharpey(’s) fiber' },
{ group: '#3 骨・軟骨', word: '外/内環状層板', meaning: 'outer/inner circumferential lamella' },
{ group: '#3 骨・軟骨', word: '骨単位', meaning: 'osteon' },
{ group: '#3 骨・軟骨', word: 'ハバース系(=骨単位)', meaning: 'Haversian system' },
{ group: '#3 骨・軟骨', word: 'ハバース管(中心管)', meaning: 'Haversian canal' },
{ group: '#3 骨・軟骨', word: 'フォルクマン管(貫通管)', meaning: 'Volkmann(’s) canal' },
{ group: '#3 骨・軟骨', word: '骨層板', meaning: 'bone lamella' },
{ group: '#3 骨・軟骨', word: '骨小腔', meaning: 'bone lacuna' },
{ group: '#3 骨・軟骨', word: '骨細管', meaning: 'bone canaliculus' },
{ group: '#3 骨・軟骨', word: '介在層板', meaning: 'interstitial lamella' },
{ group: '#3 骨・軟骨', word: '骨小柱', meaning: 'bone trabecula' },
{ group: '#4 筋組織', word: '暗調小体', meaning: 'dense body' },
{ group: '#4 筋組織', word: '筋小胞体', meaning: 'sarcoplasmic reticulum' },
{ group: '#4 筋組織', word: 'カベオラ', meaning: 'caveola' },
{ group: '#4 筋組織', word: '筋上膜', meaning: 'epimysium' },
{ group: '#4 筋組織', word: '筋周膜', meaning: 'perimysium' },
{ group: '#4 筋組織', word: '筋内膜', meaning: 'endomysium' },
{ group: '#4 筋組織', word: '筋束', meaning: 'muscle fasciculus' },
{ group: '#4 筋組織', word: '筋線維(=筋細胞)', meaning: 'muscle fiber' },
{ group: '#4 筋組織', word: '筋原線維', meaning: 'myofibril' },
{ group: '#4 筋組織', word: 'サルコメア', meaning: 'sarcomere' },
{ group: '#4 筋組織', word: 'アクチンフィラメント', meaning: 'actin filament' },
{ group: '#4 筋組織', word: 'ミオシンフィラメント', meaning: 'myosin filament' },
{ group: '#4 筋組織', word: '横細管(T細管)', meaning: 'transverse tubule' },
{ group: '#4 筋組織', word: 'Z線', meaning: 'Z line' },
{ group: '#4 筋組織', word: 'H/I/A 帯', meaning: 'H/I/A band' },
{ group: '#4 筋組織', word: '筋衛星細胞', meaning: 'satellite cell' },
{ group: '#4 筋組織', word: '筋紡錘', meaning: 'muscle spindle' },
{ group: '#4 筋組織', word: '心膜', meaning: 'pericardium' },
{ group: '#4 筋組織', word: '心膜腔', meaning: 'pericardial cavity' },
{ group: '#4 筋組織', word: '心外膜', meaning: 'epicardium' },
{ group: '#4 筋組織', word: '心筋層', meaning: 'myocardium' },
{ group: '#4 筋組織', word: '心内膜', meaning: 'endocardium' },
{ group: '#4 筋組織', word: '介在板', meaning: 'intercalated disc' },
{ group: '#5 神経組織', word: '中枢神経系', meaning: 'central nerve system' },
{ group: '#5 神経組織', word: '末梢神経系', meaning: 'peripheral nerve system' },
{ group: '#5 神経組織', word: '感覚神経細胞', meaning: 'sensory neuron' },
{ group: '#5 神経組織', word: '運動神経細胞', meaning: 'motor neuron' },
{ group: '#5 神経組織', word: '介在神経細胞', meaning: 'interneuron' },
{ group: '#5 神経組織', word: '単極細胞', meaning: 'unipolar neuron' },
{ group: '#5 神経組織', word: '双極細胞', meaning: 'bipolar neuron' },
{ group: '#5 神経組織', word: '多極細胞', meaning: 'multipolar neuron' },
{ group: '#5 神経組織', word: '偽単極細胞', meaning: 'pseudounipolar neuron' },
{ group: '#5 神経組織', word: '白質', meaning: 'white matter' },
{ group: '#5 神経組織', word: '灰白質', meaning: 'gray matter' },
{ group: '#5 神経組織', word: '細胞体', meaning: 'cell body/soma' },
{ group: '#5 神経組織', word: '樹状突起', meaning: 'dendrite' },
{ group: '#5 神経組織', word: '軸索', meaning: 'axon' },
{ group: '#5 神経組織', word: 'シナプス', meaning: 'synapse' },
{ group: '#5 神経組織', word: '軸索始起部', meaning: 'initial segment' },
{ group: '#5 神経組織', word: 'シナプス前終末', meaning: 'presynaptic terminal' },
{ group: '#5 神経組織', word: 'ニッスル小体', meaning: 'Nissl body' },
{ group: '#5 神経組織', word: 'ニューロフィラメント', meaning: 'neurofilament' },
{ group: '#5 神経組織', word: 'ニューロチューブル', meaning: 'neurotubule' },
{ group: '#5 神経組織', word: 'ミエリン鞘(髄鞘)', meaning: 'myelin sheath' },
{ group: '#5 神経組織', word: 'ランビエ絞輪', meaning: 'node of Ranvier' },
{ group: '#5 神経組織', word: 'シュミット・ランターマンの切痕', meaning: 'incisure of Schmidt-Lanterman' },
{ group: '#5 神経組織', word: '希突起膠細胞', meaning: 'oligodendroglia' },
{ group: '#5 神経組織', word: '星状膠細胞', meaning: 'astroglia' },
{ group: '#5 神経組織', word: '小膠細胞', meaning: 'microglia' },
{ group: '#5 神経組織', word: 'シュワン細胞', meaning: 'Schwann(’s) cell' },
{ group: '#5 神経組織', word: '衛星細胞', meaning: 'satellite cell' },
{ group: '#6 血管・心臓', word: '動脈', meaning: 'artery' },
{ group: '#6 血管・心臓', word: '静脈', meaning: 'vein' },
{ group: '#6 血管・心臓', word: '毛細血管', meaning: 'capillary' },
{ group: '#6 血管・心臓', word: '門脈', meaning: 'portal vein' },
{ group: '#6 血管・心臓', word: '大動脈', meaning: 'great artery' },
{ group: '#6 血管・心臓', word: '内膜、中膜、外膜', meaning: 'tunica intima/media/externa' },
{ group: '#6 血管・心臓', word: '内/外弾性板', meaning: 'internal/external elastic lamina' },
{ group: '#6 血管・心臓', word: '心内膜', meaning: 'endocardium' },
{ group: '#6 血管・心臓', word: '心外膜', meaning: 'epicardium' },
{ group: '#6 血管・心臓', word: '洞房結節', meaning: 'SA(sinoatrial) node' },
{ group: '#6 血管・心臓', word: '房室結節', meaning: 'AV(atrioventricular) node' },
{ group: '#6 血管・心臓', word: 'ヒス束', meaning: 'bundle of His' },
{ group: '#6 血管・心臓', word: '左脚/右脚', meaning: 'left/right bundle' },
{ group: '#6 血管・心臓', word: 'プルキンエ線維', meaning: 'Purkinje(’s) fiber' },
{ group: '#6 血管・心臓', word: '三尖弁', meaning: 'tricuspid valve' },
{ group: '#7 血液', word: '血清', meaning: 'serum' },
{ group: '#7 血液', word: '血漿', meaning: 'plasma' },
{ group: '#7 血液', word: '赤血球', meaning: 'red blood cell / erythrocyte' },
{ group: '#7 血液', word: '白血球', meaning: 'leukocyte' },
{ group: '#7 血液', word: 'リンパ球', meaning: 'lymphocyte' },
{ group: '#7 血液', word: 'T細胞', meaning: 'T cell' },
{ group: '#7 血液', word: 'B細胞', meaning: 'B cell' },
{ group: '#7 血液', word: '形質細胞', meaning: 'plasma cell' },
{ group: '#7 血液', word: '単球', meaning: 'monocyte' },
{ group: '#7 血液', word: 'マクロファージ', meaning: 'macrophage' },
{ group: '#7 血液', word: '顆粒球', meaning: 'granulocyte' },
{ group: '#7 血液', word: '好中球', meaning: 'neutrophil' },
{ group: '#7 血液', word: '好酸球', meaning: 'eosinophil' },
{ group: '#7 血液', word: '好塩基球', meaning: 'basophil' },
{ group: '#7 血液', word: '巨核球', meaning: 'megakaryocyte' },
{ group: '#7 血液', word: '血小板', meaning: 'platelet' },
]