       const words = [
        { group: '#0 全身に用いる単語', word: 'epi-', meaning: 'on top of' },
{ group: '#0 全身に用いる単語', word: 'peri-', meaning: 'around' },
{ group: '#0 全身に用いる単語', word: 'endo-', meaning: 'internal' },
{ group: '#0 全身に用いる単語', word: 'pro-', meaning: 'before' },
{ group: '#0 全身に用いる単語', word: 'para-', meaning: 'above, beside' },
{ group: '#0 全身に用いる単語', word: '-cyte', meaning: '-細胞' },
{ group: '#0 全身に用いる単語', word: '-blast', meaning: '-芽細胞(-を産生する細胞)' },
{ group: '#0 全身に用いる単語', word: '-ulus', meaning: '小～, small-' },
{ group: '#0 全身に用いる単語', word: 'medulla', meaning: '髄質' },
{ group: '#0 全身に用いる単語', word: 'cortex', meaning: '皮質' },
{ group: '#0 全身に用いる単語', word: 'capsule', meaning: '被膜' },
{ group: '#0 全身に用いる単語', word: 'corpuscle / body', meaning: '小体' },
{ group: '#0 全身に用いる単語', word: 'membrane', meaning: '膜' },
{ group: '#0 全身に用いる単語', word: 'tunica', meaning: '被膜, 層' },
{ group: '#0 全身に用いる単語', word: 'plexus', meaning: '叢, 網状組織' },
{ group: '#0 全身に用いる単語', word: 'lamina', meaning: '薄層, 板' },
{ group: '#0 全身に用いる単語', word: 'lamella', meaning: '薄板' },
{ group: '#0 全身に用いる単語', word: 'trabecula', meaning: '索(大綱)' },
{ group: '#0 全身に用いる単語', word: 'cavity', meaning: '腔' },
{ group: '#0 全身に用いる単語', word: 'papillae', meaning: '乳頭' },
{ group: '#0 全身に用いる単語', word: 'sheath', meaning: '鞘' },
{ group: '#0 全身に用いる単語', word: 'sphincter', meaning: '括約筋' },
{ group: '#0 全身に用いる単語', word: 'gland', meaning: '腺' },
{ group: '#0 全身に用いる単語', word: 'serous', meaning: '漿液性の' },
{ group: '#0 全身に用いる単語', word: 'mucous', meaning: '粘液性の' },
{ group: '#0 全身に用いる単語', word: 'duct', meaning: '管' },
{ group: '#0 全身に用いる単語', word: 'tubule / tubuli', meaning: '細管' },
{ group: '#0 全身に用いる単語', word: 'canaliculus', meaning: '毛細管' },
{ group: '#0 全身に用いる単語', word: 'arteriole', meaning: '小動脈' },
{ group: '#0 全身に用いる単語', word: 'reticulum', meaning: '細網' },
{ group: '#0 全身に用いる単語', word: 'follicle', meaning: '濾胞, 小胞' },
{ group: '#0 全身に用いる単語', word: 'node', meaning: 'こぶ, 結節' },
{ group: '#0 全身に用いる単語', word: 'plasma', meaning: '形質, プラズマ' },
{ group: '#1 上皮', word: 'epithelium', meaning: '上皮' },
{ group: '#1 上皮', word: 'endothelium', meaning: '内皮' },
{ group: '#1 上皮', word: 'simple', meaning: '単層' },
{ group: '#1 上皮', word: 'stratified', meaning: '重層' },
{ group: '#1 上皮', word: 'squamous', meaning: '扁平' },
{ group: '#1 上皮', word: 'cuboidal', meaning: '立方' },
{ group: '#1 上皮', word: 'columnar', meaning: '円柱' },
{ group: '#1 上皮', word: '(un/)keratinized', meaning: '(非/)角化' },
{ group: '#1 上皮', word: 'pseudostratified', meaning: '偽重層(多列)' },
{ group: '#1 上皮', word: 'transitional', meaning: '移行' },
{ group: '#1 上皮', word: 'basal membrane', meaning: '基底膜' },
{ group: '#1 上皮', word: 'ciliated cell', meaning: '繊毛細胞' },
{ group: '#1 上皮', word: 'basal cell', meaning: '基底細胞' },
{ group: '#1 上皮', word: 'goblet cell', meaning: '杯細胞' },
{ group: '#1 上皮', word: 'brush border', meaning: '刷子縁' },
{ group: '#1 上皮', word: 'cilia', meaning: '繊毛' },
{ group: '#1 上皮', word: 'villi', meaning: '絨毛' },
{ group: '#1 上皮', word: 'microvilli', meaning: '微絨毛' },
{ group: '#1 上皮', word: 'actin filament', meaning: 'アクチンフィラメント' },
{ group: '#1 上皮', word: 'intermediate filament', meaning: '中間径フィラメント' },
{ group: '#1 上皮', word: 'microtubule', meaning: '微小管' },
]