       const words = [
        { group: '#0 全身に用いる単語', word: 'epi-', meaning: 'on top of' },
{ group: '#0 全身に用いる単語', word: 'peri-', meaning: 'around' },
{ group: '#0 全身に用いる単語', word: 'endo-', meaning: 'internal' },
{ group: '#0 全身に用いる単語', word: 'pro-', meaning: 'before' },
{ group: '#0 全身に用いる単語', word: 'para-', meaning: 'above, beside' },
{ group: '#0 全身に用いる単語', word: '-cyte', meaning: '-細胞' },
{ group: '#0 全身に用いる単語', word: '-blast', meaning: '-芽細胞(-を産生する細胞)' },
{ group: '#0 全身に用いる単語', word: '-ulus', meaning: '小～, small-' },
{ group: '#0 全身に用いる単語', word: 'medulla', meaning: '髄質' },
{ group: '#0 全身に用いる単語', word: 'cortex', meaning: '皮質' },
{ group: '#0 全身に用いる単語', word: 'capsule', meaning: '被膜' },
{ group: '#0 全身に用いる単語', word: 'corpuscle / body', meaning: '小体' },
{ group: '#0 全身に用いる単語', word: 'membrane', meaning: '膜' },
{ group: '#0 全身に用いる単語', word: 'tunica', meaning: '被膜, 層' },
{ group: '#0 全身に用いる単語', word: 'plexus', meaning: '叢, 網状組織' },
{ group: '#0 全身に用いる単語', word: 'lamina', meaning: '薄層, 板' },
{ group: '#0 全身に用いる単語', word: 'lamella', meaning: '薄板' },
{ group: '#0 全身に用いる単語', word: 'trabecula', meaning: '索(大綱)' },
{ group: '#0 全身に用いる単語', word: 'cavity', meaning: '腔' },
{ group: '#0 全身に用いる単語', word: 'papillae', meaning: '乳頭' },
{ group: '#0 全身に用いる単語', word: 'sheath', meaning: '鞘' },
{ group: '#0 全身に用いる単語', word: 'sphincter', meaning: '括約筋' },
{ group: '#0 全身に用いる単語', word: 'gland', meaning: '腺' },
{ group: '#0 全身に用いる単語', word: 'serous', meaning: '漿液性の' },
{ group: '#0 全身に用いる単語', word: 'mucous', meaning: '粘液性の' },
{ group: '#0 全身に用いる単語', word: 'duct', meaning: '管' },
{ group: '#0 全身に用いる単語', word: 'tubule / tubuli', meaning: '細管' },
{ group: '#0 全身に用いる単語', word: 'canaliculus', meaning: '毛細管' },
{ group: '#0 全身に用いる単語', word: 'arteriole', meaning: '小動脈' },
{ group: '#0 全身に用いる単語', word: 'reticulum', meaning: '細網' },
{ group: '#0 全身に用いる単語', word: 'follicle', meaning: '濾胞, 小胞' },
{ group: '#0 全身に用いる単語', word: 'node', meaning: 'こぶ, 結節' },
{ group: '#0 全身に用いる単語', word: 'plasma', meaning: '形質, プラズマ' },
{ group: '#1 上皮', word: 'epithelium', meaning: '上皮' },
{ group: '#1 上皮', word: 'endothelium', meaning: '内皮' },
{ group: '#1 上皮', word: 'simple', meaning: '単層' },
{ group: '#1 上皮', word: 'stratified', meaning: '重層' },
{ group: '#1 上皮', word: 'squamous', meaning: '扁平' },
{ group: '#1 上皮', word: 'cuboidal', meaning: '立方' },
{ group: '#1 上皮', word: 'columnar', meaning: '円柱' },
{ group: '#1 上皮', word: '(un/)keratinized', meaning: '(非/)角化' },
{ group: '#1 上皮', word: 'pseudostratified', meaning: '偽重層(多列)' },
{ group: '#1 上皮', word: 'transitional', meaning: '移行' },
{ group: '#1 上皮', word: 'basal membrane', meaning: '基底膜' },
{ group: '#1 上皮', word: 'ciliated cell', meaning: '繊毛細胞' },
{ group: '#1 上皮', word: 'basal cell', meaning: '基底細胞' },
{ group: '#1 上皮', word: 'goblet cell', meaning: '杯細胞' },
{ group: '#1 上皮', word: 'brush border', meaning: '刷子縁' },
{ group: '#1 上皮', word: 'cilia', meaning: '繊毛' },
{ group: '#1 上皮', word: 'villi', meaning: '絨毛' },
{ group: '#1 上皮', word: 'microvilli', meaning: '微絨毛' },
{ group: '#1 上皮', word: 'actin filament', meaning: 'アクチンフィラメント' },
{ group: '#1 上皮', word: 'intermediate filament', meaning: '中間径フィラメント' },
{ group: '#1 上皮', word: 'microtubule', meaning: '微小管' },
{ group: '#2 結合組織', word: 'loose connective tissue', meaning: '疎性結合組織' },
{ group: '#2 結合組織', word: 'dense connective tissue', meaning: '強靭(密性)結合組織' },
{ group: '#2 結合組織', word: 'reticular connective tissue', meaning: '細網組織' },
{ group: '#2 結合組織', word: 'adipose tissue', meaning: '脂肪組織' },
{ group: '#2 結合組織', word: 'mucous connective tissue', meaning: '膠様組織' },
{ group: '#2 結合組織', word: 'collagen fiber', meaning: 'コラーゲン線維(膠原線維)' },
{ group: '#2 結合組織', word: 'reticular fiber', meaning: '細網線維' },
{ group: '#2 結合組織', word: 'elastic fiber', meaning: '弾性線維' },
{ group: '#2 結合組織', word: 'fibroblast', meaning: '線維芽細胞' },
{ group: '#2 結合組織', word: 'reticular cell', meaning: '細網細胞' },
{ group: '#2 結合組織', word: 'adipocyte', meaning: '脂肪細胞' },
{ group: '#2 結合組織', word: 'mast cell', meaning: '顆粒細胞(肥満細胞)' },
{ group: '#2 結合組織', word: 'zonula occludens', meaning: '閉鎖帯' },
{ group: '#2 結合組織', word: 'tight junction', meaning: 'タイト結合(=閉鎖帯)' },
{ group: '#2 結合組織', word: 'zonula adherens', meaning: '接着帯' },
{ group: '#2 結合組織', word: 'desmosome', meaning: 'デスモソーム(接着斑)' },
{ group: '#2 結合組織', word: 'terminal bar', meaning: '閉鎖堤' },
{ group: '#2 結合組織', word: 'junctional complex', meaning: '接着複合体' },
{ group: '#2 結合組織', word: 'focal adhesion', meaning: 'フォーカルアドヒージョン(局所接着)' },
{ group: '#2 結合組織', word: 'hemidesmosome', meaning: 'ヘミデスモソーム' },
{ group: '#2 結合組織', word: 'gap junction', meaning: 'ギャップ結合' },
{ group: '#3 骨・軟骨', word: 'chondroprogenitor cell', meaning: '軟骨前駆細胞' },
{ group: '#3 骨・軟骨', word: 'chondroblast', meaning: '軟骨芽細胞' },
{ group: '#3 骨・軟骨', word: 'chondrocyte', meaning: '軟骨細胞' },
{ group: '#3 骨・軟骨', word: 'cartilage lacuna', meaning: '軟骨小腔' },
{ group: '#3 骨・軟骨', word: 'perichondrium', meaning: '軟骨膜' },
{ group: '#3 骨・軟骨', word: 'hyaline cartilage', meaning: '硝子(ガラス)軟骨' },
{ group: '#3 骨・軟骨', word: 'elastic cartilage', meaning: '弾性軟骨' },
{ group: '#3 骨・軟骨', word: 'fibrocartilage', meaning: '線維軟骨' },
{ group: '#3 骨・軟骨', word: 'osteoprogenitor cell', meaning: '骨原性細胞' },
{ group: '#3 骨・軟骨', word: 'osteoblast', meaning: '骨芽細胞' },
{ group: '#3 骨・軟骨', word: 'osteocyte', meaning: '骨細胞' },
{ group: '#3 骨・軟骨', word: 'osteoclast', meaning: '破骨細胞' },
{ group: '#3 骨・軟骨', word: 'compact bone', meaning: '緻密骨' },
{ group: '#3 骨・軟骨', word: 'spongy bone', meaning: '海綿骨' },
{ group: '#3 骨・軟骨', word: 'medullary cavity', meaning: '髄腔' },
{ group: '#3 骨・軟骨', word: 'periosteum', meaning: '骨膜' },
{ group: '#3 骨・軟骨', word: 'outer fibrous layer', meaning: '外側線維層' },
{ group: '#3 骨・軟骨', word: 'inner cellular layer', meaning: '内側細胞層' },
{ group: '#3 骨・軟骨', word: 'Sharpey(’s) fiber', meaning: 'シャーピー線維' },
{ group: '#3 骨・軟骨', word: 'outer/inner circumferential lamella', meaning: '外/内環状層板' },
{ group: '#3 骨・軟骨', word: 'osteon', meaning: '骨単位' },
{ group: '#3 骨・軟骨', word: 'Haversian system', meaning: 'ハバース系(=骨単位)' },
{ group: '#3 骨・軟骨', word: 'Haversian canal', meaning: 'ハバース管(中心管)' },
{ group: '#3 骨・軟骨', word: 'Volkmann(’s) canal', meaning: 'フォルクマン管(貫通管)' },
{ group: '#3 骨・軟骨', word: 'bone lamella', meaning: '骨層板' },
{ group: '#3 骨・軟骨', word: 'bone lacuna', meaning: '骨小腔' },
{ group: '#3 骨・軟骨', word: 'bone canaliculus', meaning: '骨細管' },
{ group: '#3 骨・軟骨', word: 'interstitial lamella', meaning: '介在層板' },
{ group: '#3 骨・軟骨', word: 'bone trabecula', meaning: '骨小柱' },
]